// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StarTEDSystem.Entities
{
    public partial class Position
    {
        public Position()
        {
            Employees = new HashSet<Employee>();
            InverseReportsToNavigation = new HashSet<Position>();
        }

        [Key]
        public int PositionID { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Description { get; set; }
        public int? ReportsTo { get; set; }

        [ForeignKey("ReportsTo")]
        [InverseProperty("InverseReportsToNavigation")]
        public virtual Position ReportsToNavigation { get; set; }
        [InverseProperty("Position")]
        public virtual ICollection<Employee> Employees { get; set; }
        [InverseProperty("ReportsToNavigation")]
        public virtual ICollection<Position> InverseReportsToNavigation { get; set; }
    }
}